name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker images
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        run: |
          # List of microservices with correct paths
          services=("src/frontend")

          # Build and push images for each service
          for service in "${services[@]}"; do
            service_name=$(basename $service)
            docker build -t $ECR_REGISTRY/eboutique/$service_name:latest $service
            docker push $ECR_REGISTRY/eboutique/$service_name:latest
          done

      - name: Set up kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name eboutique-cluster --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          # Apply Kubernetes manifests
          kubectl apply -k kubernetes-manifests/

          # Update images in deployments
          kubectl set image deployment/frontend server=${{ steps.ecr-login.outputs.registry }}/eboutique/frontend:latest

