name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}

      - name: Build and Push Docker Images
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
        run: |
          # Define the services under the src/ directory
          services=("adservice" "cartservice" "checkoutservice" "currencyservice" "emailservice" "frontend" "paymentservice" "productcatalogservice" "recommendationservice" "shippingservice")

          for service in "${services[@]}"; do
            service_path="src/$service"
            if [ -d "$service_path" ]; then
              echo "Building and pushing $service..."
              docker build -t $ECR_REGISTRY/eboutique/$service:latest $service_path
              docker push $ECR_REGISTRY/eboutique/$service:latest
            else
              echo "Directory $service_path not found, skipping..."
            fi
          done

      - name: Update Kubernetes Deployment
        run: |
          services=("adservice" "cartservice" "checkoutservice" "currencyservice" "emailservice" "frontend" "paymentservice" "productcatalogservice" "recommendationservice" "shippingservice")
          for service in "${services[@]}"; do
            kubectl set image deployment/$service $service=${{ secrets.AWS_ECR_REGISTRY }}/eboutique/$service:latest
          done
