name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REGISTRY }}

      - name: Build and Push Docker Images
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
        run: |
          # Build and push each service
          services=("frontend" "adservice" "cartservice")  # Add all services here
          for service in "${services[@]}"; do
            docker build -t $ECR_REGISTRY/eboutique/$service:latest ./$service
            docker push $ECR_REGISTRY/eboutique/$service:latest
          done

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/frontend frontend=${{ secrets.AWS_ECR_REGISTRY }}/eboutique/frontend:latest

